---
editor_options: 
  markdown: 
    wrap: 72
---


# Dengue in Thailand

## Does Bangkok have a central role in the dengue dynamics of Thailand?

<https://parasitesandvectors.biomedcentral.com/articles/10.1186/s13071-020-3892-y>

## Clinical and epidemiologic characteristics associated with dengue fever in 2011-2016 in Bang Phae district, Ratchaburi province, Thailand

<https://journals.plos.org/plosntds/article?id=10.1371/journal.pntd.0009513>

## Are we modelling the correct dataset? Minimizing false predictions for dengue fever in Thailand

<https://www.cambridge.org/core/journals/epidemiology-and-infection/article/are-we-modelling-the-correct-dataset-minimizing-false-predictions-for-dengue-fever-in-thailand/747AE7867C566B28F047623199298D04>

-   susceptible-infected-recovered (SIR) type model
-   respective state space plots

## Economic impact of dengue fever/dengue hemorrhagic fever in Thailand at the family and population levels

<https://www.ajtmh.org/view/journals/tpmd/72/6/article-p786.xml>

## Geographical structure of dengue transmission and its determinants in Thailand

<https://www.cambridge.org/core/journals/epidemiology-and-infection/article/geographical-structure-of-dengue-transmission-and-its-determinants-in-thailand/97D0F8EE84FCDE429C806F9EE8950631>


# Precipitation (Thailand)

## Projection of the Precipitation Extremes in Thailand Under Climate Change Scenario RCP8.5

<https://www.frontiersin.org/articles/10.3389/fenvs.2021.657810/full>

-   annual precipitation total: decreasing trend in eastern Thailand, increasing trend in northern Thailand
-   annual number of rainy days: decreasing trend in Thailand
-   consecutive wet days: widespread decreasing trend in most regions (drastic decline in southern Thailand)

## Multiple comparisons of precipitation variations in different areas using simultaneous confidence intervals for all possible ratios of variances of several zero-inflated lognormal models

<https://peerj.com/articles/12659/>


# The impact of climate on dengue (general reports)

## A regional suitable conditions index to forecast the impact of climate change on dengue vectorial capacity

<https://researchonline.lshtm.ac.uk/id/eprint/4661319/3/Regional_suitable_index.pdf>

## Effects of ambient temperature and precipitation on the risk of dengue fever: A systematic review and updated meta-analysis

<https://www-sciencedirect-com.ubproxy.ub.uni-heidelberg.de/science/article/pii/S0013935120309403?via%3Dihub>

-   dengue virus in tropical and sub-tropical regions
-   2 Aedes mosquito types: *Aedes aegypti* and *Aedes albopictus*
-   1970: dengue fever in 9 countries
-   now more than 100 countries
-   extreme weather events cause more clustered disease outbreaks
-   precipitation also affects dengue fever outbreaks

## A stage structured mosquito model incorporating effects of precipitation and daily temperature fluctuations

<https://gala.gre.ac.uk/id/eprint/15846/7/15846%20CHEKE_Stage_Structured_Mosquito_Model_2016.pdf>

## Dengue disease dynamics are modulated by the combined influences of precipitation and landscape: A machine learning approac

<https://www.sciencedirect.com/science/article/pii/S004896972103477X?via%3Dihub>

## Temporal relationship between environmental factors and the occurrence of dengue fever

<https://www.webofscience.com/wos/biosis/full-record/BIOSIS:PREV201400626986>


# The impact of climate on dengue (Thailand based reports)

## Association between climate variables and dengue incidence in Nakhon Si Thammarat Province, Thailand

<https://www.geospatialhealth.net/index.php/gh/article/view/1012/1005/>

**Plots**
- Denuge cases per province in split areas (Fig 2)
- Dengue peaks over years and months (Fig 3,4)
- Rainfall in bars and dengue cases as curve --> similar peaks? (Fig 6)

**Methods:**
- complex non linear interactions
- poisson propability distribution of generalized linear model (GLM) --> association between monthly weather data and dengue cases (2002-2018)
- Geographic information systems (GIS)
- spatial autocorrelation analysis
- cluster analysis
- tempral analysis
- Hotspots: focus on statistically significant hotspots (high value and surrounding provinces with also high values), same for coldspots

**Einführung**
- Thailand: Tropical climate --> encourages very high mosquito densities in some areas of Thailand
- ideal for dengue transmission, especially in southern region
- Longest dengue fever transmission duration: Nakhon Si Thammarat --> affected by rainfall, rainy days, temperature and humidity (from June to September) others in South (June-August)
- Risk of dengue incidence occuring during rainy season twice as high as during monsoon
- climate change (temperature, precipitation, **extreme weather events**) influences geographical distribution and incidences of vector-borne diseases like dengue
- Important driver + predictor if dengue epidemic Thailand: El-Nino Southern Oscillation (ENSO) --> occurs periodically (natural weather phenomenon)
- OPTIMAL PUBLIC HEALTH RESPOND: direction and extent of climate effects need to be predicted 
- 75% of global population with dengue is in Asia Pacific --> causes highest hospitalizations and deaths in children
(in those regions: 1,3 billion people at risk, 2011)
- Dengue epidemics in southeast Asia: occur in regular cycle of 3 tp 5 years
- In Thailand: disease severity and cases increasing


## Spatiotemporal patterns and climatic drivers of severe dengue in Thailand

<https://researchonline.lshtm.ac.uk/id/eprint/4650940/6/Xu-etal-2018-Spatiotemporal-patterns-and-climatic-drivers-of-severe-dengue-in-Thailand.pdf>

-   3 objectives: identify high-risk clusters of dengue, compare inter-annual seasonality in different provinces and quantify associations of temperature and relative humidity with dengue
-   they used GLM and DLNM as methods
-   ideas:
    -   graph of dengue over time from 2006-2020 (like Fig. 1)
    -   spatial patterns and identifying hot-spots of both dengue and rainfall in Thailand (for each month/year or something else) (like Fig. 2)
    -   looking at seasonality changes (like Fig. 3)
    -   is there a optimal/favored precipitation for dengue?
-   seasonality changed in Central, Eastern and Southern Thailand but was stable in Northern/Northeastern Thailand
-   mean temperature and humidity affect dengue occurence significantly
-   different regions were affected differently
    -   some regions more affected by temperature
    -   some regions more affected by humidity
-   cases peaked from June to August
-   increased temperature speeds up dengue virus replication rate and extrinsic incubation period
-   dengue cases clustered in certain provinces but the cluster location changed across the years

## Spatio-temporal climate-based model of dengue infection in Southern, Thailand

<https://europepmc.org/article/MED/33579141>

## Knowledge, attitudes, and practices on climate change and dengue in Lao People's Democratic Republic and Thailand

<https://www.sciencedirect.com/science/article/pii/S0013935120314067?via%3Dihub>

## Multiyear Climate Variability and Dengue---El Niño Southern Oscillation, Weather, and Dengue Incidence in Puerto Rico, Mexico, and Thailand: A Longitudinal Data Analysis

<https://journals.plos.org/plosmedicine/article?id=10.1371/journal.pmed.1000168>

## The association between dengue incidences and provincial-level weather variables in Thailand from 2001 to 2014

<https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0226945>

# The impact of climate on dengue (reports based on other locations)

## The impacts of precipitation patterns on dengue epidemics in Guangzhou city

<https://link.springer.com/article/10.1007/s00484-021-02149-2>

## Local and Global Effects of Climate on Dengue Transmission in Puerto Rico

<https://journals.plos.org/plosntds/article?id=10.1371/journal.pntd.0000382>

## Effects of Extreme Precipitation to the Distribution of Infectious Diseases in Taiwan, 1994-2008

<https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0034651>


# General Review of all reviews

<https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9197220/>


# seasonality

## Seasonal forecasting of Thailand summer monsoon rainfall

<https://doi.org/10.1002/joc.1144>


# notes wednesday

Mobility Data

Temperature Precipitation Humidity

Monthly Data 2003 - 2020

-   Hypothesis unbiased
-   Based on Literature
-   Background slide about biological mechanism

AREMA Model GAM Model for Prediction

First descriptive analysis correlation Analysis and .... Tools for plotting maps Environmental Variables

17.05 Project Proposal.

Spacial Temporal Analysis Plotting Graphs Model Data
