
```{r}
centroids <- read.table(file = "Regions, Longtitude, Latitude.csv",  sep = "|", header = TRUE)

#"|"
centroids
class(centroids)
#Table with Region; Latitude; Longtitude
```

```{r}
library(sf)
Thailand_Shape = st_read("gadm36_THA_shp/gadm36_THA_1.shp")
list(Thailand_Shape$NAME_1)
View(Thailand_Shape)

ShapeData = as.data.frame(Thailand_Shape[,4])
#View(ShapeData)
ShapeDataFinal = as.data.frame(ShapeData[,1])
#View(ShapeDataFinal)

# Print the updated list
ergebnis = as.data.frame(province_names)[,1] %in% ShapeDataFinal[,1]
which(ergebnis == F)
as.data.frame(province_names)[which((as.data.frame(province_names)[,1] %in% ShapeDataFinal[,1]) == FALSE),1]

#Bangkok
```

```{r}
# load dplyr and tidyr library
library(dplyr)
library(tidyr)

centroids <- centroids %>% separate(ADM1_EN.Longitude.Latitude, c('Province','Longtitude',"Latitude"), sep = ";")
centroids

```

```{r}
Thailand_Shape$NAME_1[Thailand_Shape$NAME_1 == "Bangkok Metropolis"] <- "Bangkok" 
View(Thailand_Shape)

# Adjust column header
names(Thailand_Shape)[4]  <- "Districts_names"
# Adjust column header
names(centroids)[1]  <- "Districts_names"
```

```{r}
library(dplyr)

colnames(Population)[2]="Districts_names"
Population

colnames(Precipitation)[2]="Districts_names"

geo_data <- left_join(x = centroids, y = Thailand_Shape, by = c("Districts_names"))

geo_data_pop <- left_join(x= Population, y = geo_data, by = c("Districts_names"))
View(geo_data_pop)
geo_data_pop_sf <- st_as_sf(geo_data_pop)
class(geo_data_pop_sf)

geo_data_prec <- left_join(x = Precipitation[, -c(3, 4)], y = geo_data, by = c("Districts_names"))
View(geo_data_prec)
geo_data_prec_sf <- st_as_sf(geo_data_prec)

head(geo_data)
class(geo_data)
summary(geo_data)
str(geo_data)      
names(geo_data)
View(geo_data)
```

```{r}
# create an sf object for plotting
geo_data <- sf::st_as_sf(geo_data)
class(geo_data)

# [1] "sf"         "data.frame"

# plot with basic plot function of R
#plot(geo_data) # "all data columns" are plotted
```
```{r}
library(ggplot2)
ggplot()+
  geom_sf (data = geo_data, col = "black", fill = NA)
 
 
```

```{r}
Thailand_provinces_ggplot <- 
  ggplot(geo_data) +
  geom_sf(fill = "yellow") +
  geom_sf_text(
    aes(label = Districts_names),
    size = 1,
    hjust = 1
  )
Thailand_provinces_ggplot


Bangkok_ChangRai_Label <- filter(geo_data,
                         Districts_names %in% c("Chiang Mai", "Chiang Rai", "Lampang", "Lamphun", "Mae Hong Son", "Nan", "Phayao", "Phrae", "Uttaradit"))

Thailand_provinces_Specific <- ggplot() +
  geom_sf(data = geo_data,
          col = NA) +
  geom_sf(data = Bangkok_ChangRai_Label,
          aes(linetype = Districts_names,
              fill = Districts_names)) +
  scale_fill_brewer(palette = "Dark3") +
  labs(
    caption = "Caption",
    fill = "Northern Region",
    linetype = "Northern Region",
    x = "Longitude",
    y = "Latitude"
  ) + theme_bw()


Thailand_provinces_Specific
```

```{r}
geo_data$District_Group <- ifelse(geo_data$Districts_names %in% c("Chiang Mai", "Chiang Rai", "Lampang", "Lamphun", "Mae Hong Son", "Nan", "Phayao", "Phrae", "Uttaradit"), "Northern Provinces",
                                  ifelse(geo_data$Districts_names %in% c("Amnat Charoen", "Bueng Kan", "Buri Ram", "Chaiyaphum", "Kalasin", "Khon Kaen", "Loei", "Maha Sarakham", "Mukdahan", "Nakhon Phanom", "Nakhon Ratchasima", "Nong Bua Lam Phu", "Nong Khai", "Roi Et", "Sakon Nakhon", "Si Sa Ket", "Surin", "Ubon Ratchathani", "Udon Thani", "Yasothon"), "North-Eastern Provinces",
                                         ifelse(geo_data$Districts_names %in% c("Chumphon", "Krabi", "Nakhon Si Thammarat", "Narathiwat", "Pattani", "Phangnga", "Phatthalung", "Phuket", "Ranong", "Satun", "Songkhla", "Surat Thani", "Trang", "Yala"), "Southern Provinces",
                                                "Central Provinces")))

# Create a ggplot object and plot the sf data
my_plot <- ggplot() +
  geom_sf(data = geo_data,
          aes(linetype = District_Group,
              fill = District_Group)) + scale_fill_brewer(palette = "Dark2") + theme_bw()
my_plot
```


```{r}
library(ggplot2)
library(viridis)

years <- c("2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020")

for (year in years) {
  pop_plot <- ggplot() +
    geom_sf(data = geo_data_pop_sf, aes(fill = !!as.name(year)), alpha = 0.95) +
    ggtitle(label = "Population Data", subtitle = year) +
    labs(x = "Latitude", y = "Longitude") +
    scale_fill_viridis(option = "plasma", direction = -1) +
    geom_sf_text(data = geo_data_pop_sf, aes(label = Districts_names), size = 1, hjust = 1)
  
  print(pop_plot)
}

```


```{r}
library(ggplot2)
library(viridis)

Month2020 <- c("2020.01.", "2020.02.", "2020.03.", "2020.04.", "2020.05.", "2020.06.", "2020.07.", "2020.08.", "2020.09.", "2020.10.", "2020.11.", "2020.12.")

#scale_limits = (0:700)

for (Month in Month2020) {
  prec_plot <- ggplot() +
    geom_sf(data = geo_data_prec_sf, aes(fill = !!as.name(Month)), alpha = 0.95) +
    ggtitle(label = "Precipitation Data", subtitle = Month) +
    labs(x = "Latitude", y = "Longitude") +
    scale_fill_viridis(option = "plasma", direction = -1, limits= range(0:700), name = "Rainfall [mm]"
  ) +
    geom_sf_text(data = geo_data_prec_sf, aes(label = Districts_names), size = 1, hjust = 1)
  
  print(prec_plot)
}
```

#Plot dot plot with relative incidenz over Precipitation plot, and take time lagging into consideration

Monthly table without time lag Relative Incidence (comnbined)
Monthly Time Lag Table(1 Monat) Relative Incidence (combined + lag)
Yearly Incidence pro province change over the years (added up pro province jeden monat)



```{r}
# Left: use size and color
library(ggplot2)
library(viridis)

Month2020 <- c("2020.01.", "2020.02.", "2020.03.", "2020.04.", "2020.05.", "2020.06.", "2020.07.", "2020.08.", "2020.09.", "2020.10.", "2020.11.", "2020.12.")

#scale_limits = (0:700)

for (Month in Month2020) {
  prec_plot <- ggplot() +
    geom_sf(data = geo_data_prec_sf, aes(fill = !!as.name(Month)), alpha = 0.95) +
    ggtitle(label = "Precipitation Data", subtitle = Month) +
    geom_point( data=geo_data_pop_sf, aes(x=Longtitude, y=Latitude, size=2020, color=2020)) +
    labs(x = "Latitude", y = "Longitude") +
    scale_fill_viridis(option = "plasma", direction = -1, limits= range(0:700), name = "Rainfall [mm]"
  ) +
    geom_sf_text(data = geo_data_prec_sf, aes(label = Districts_names), size = 1, hjust = 1)+
  coord_sf(lims = "geometry_bbox")
  print(prec_plot)
}




  
```
```{r}
#library(ggplot2)
#library(viridis)

#Month2020 <- c("2020.01.", "2020.02.", "2020.03.", "2020.04.", "2020.05.", "2020.06.", "2020.07.", "2020.08.", "2020.09.", "2020.10.", "2020.11.", "2020.12.")

#for (Month in Month2020) {
  #prec_plot <- ggplot() +
    #geom_sf(data = geo_data_prec_sf, aes(fill = !!as.name(Month)), alpha = 0.95) +
   # ggtitle(label = "Precipitation Data", subtitle = Month) +
    
    #geom_point(data = geo_data_pop, aes(x = Longtitude, y = Latitude, size = geo_data_pop_sf$"2020", color = geo_data_pop_sf$"2020"),position = "identity") +
    
    
    #labs(x = "Latitude", y = "Longitude") +
    #scale_fill_viridis(option = "plasma", direction = -1, name = "Rainfall [mm]") +
   # geom_sf_text(data = geo_data_prec_sf, aes(label = Districts_names), size = 1, hjust = 1) +
   # coord_sf(lims = "geometry_bbox")

 # print(prec_plot)
}


```

```{r}
library(ggplot2)
library(viridis)
library(sf)

prec_plot <- ggplot() +
    geom_sf(data = geo_data_prec_sf, aes(fill = `2020.01.`), alpha = 0.95) +
    ggtitle(label = "Precipitation Data", subtitle = "Month") +
    geom_point(data = geo_data_pop_sf, aes(x = Longtitude, y = Latitude, size = `2020`)) +
    labs(x = "Longitude", y = "Latitude") +
    scale_fill_viridis(option = "plasma", direction = -1, name = "Rainfall [mm]") +
    geom_sf_text(data = geo_data_prec_sf, aes(label = Districts_names), size = 1, hjust = 1) +
    #coord_sf()
    #coord_sf(default_crs = st_crs(4326))
    coord_sf(lims = "geometry_bbox")
    #coord_sf(default_crs = st_crs(3857))

prec_plot



```
```{r}


  


#for (Month in Month2020.01) {
 # prec_plot <- ggplot() +
  #  geom_sf(data = geo_data_prec_sf, aes(fill = !!as.name(Month)), alpha = 0.95) +
  #  ggtitle(label = "Precipitation Data", subtitle = Month) +
    
  #  geom_point(data = geo_data_pop, aes(x = Longtitude, y = Latitude, size = `2020`))+
    
  #  labs(x = "Longtitude", y = "Latitude") +
  #  scale_fill_viridis(option = "plasma", direction = -1, name = "Rainfall [mm]") +
  #  geom_sf_text(data = geo_data_prec_sf, aes(label = Districts_names), size = 1, hjust = 1) +
  #  coord_sf(default_crs = st_crs(4326))

#prec_plot
}
```

```{r}
#Show this Version? 


#colnames(geo_data_prec_sf)

library(ggplot2)
library(viridis)

prec_plot <- ggplot() +
  geom_sf(data = geo_data_prec_sf, aes(fill = `2020.01.`), alpha = 0.95) +
  #ggtitle(label = "Precipitation Data", subtitle = "Month") +
  #labs(x = "Latitude", y = "Longtitude") +
  #scale_fill_viridis(option = "plasma", direction = -1, name = "Rainfall [mm]") +
  #geom_sf_text(data = geo_data_prec_sf, aes(label = Districts_names), size = 1, hjust = 1) +
  geom_point(data = geo_data_pop_sf, mapping = aes(x = `Longtitude`, y = `Latitude`, size = `2020`)) +
  #coord_sf(lims = "geometry_bbox")
  #coord_sf()
  #coord_sf(default_crs = NULL)
  #coord_sf(default_crs = st_crs(4326))
  coord_sf(lims = "geometry_bbox")
  #coord_sf(default_crs = st_crs(3857))


prec_plot

```

```{r}
d=data.frame(beauty=c(1,2,6,4,4,6,7,8), intelligence=c(8,4,7,5,4,9,2,3), speed=c(7,6,9,5,7,6,7,8), gender=c('m','m','f','m','f','f','f','m'))
ggplot() + 
geom_point(data=d, mapping=aes(x=intelligence, y=beauty, shape=gender, color=gender, size=speed))
coord_sf()
```

GAM Models

